### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by donald-richardson-dxd** [song940/node-ntp#8]
Running the example gives:

```
  name = 'NTP Timeout Error'
       ^

SyntaxError: Unexpected token =
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\CPU01-01\Documents\Projects\gensler-ntp\inde
x.js:1:75)
```

**Comment by lsongdev** [comment]
Upgrade your Node.js version to latest.
